/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author abraham-alvarez
 */
public class FrmMecanicos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMecanicos.class.getName());

    /**
     * Creates new form FrmMecanicos
     */
    public FrmMecanicos() {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cargarTabla();
        
    }
    
    
    private void cargarTabla() {
        String[] columnas = {"ID", "DPI/NIT", "Nombre", "Especialidad"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        Dao.MecanicoDAO dao = new Dao.MecanicoDAO();
        java.util.List<Modelo.Mecanico> lista = dao.listarMecanicos();
        
        for (Modelo.Mecanico m : lista) {
            Object[] fila = new Object[4];
            fila[0] = m.getIdMecanico();
            fila[1] = m.getIdentificador();
            fila[2] = m.getNombre();
            fila[3] = m.getEspecialidad();
            modelo.addRow(fila);
        }
        tbMecanicos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMecanicos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DPI / NIT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("ESPECIALIDAD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(txtIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));
        getContentPane().add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, -1));

        btnGuardar.setText("GUARDAR MECANICO");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 210, 30));

        tbMecanicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMecanicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMecanicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMecanicos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 370, 190));

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 224, 130, 40));

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 224, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //// 1. Capturamos los textos
        String identificador = txtIdentificador.getText().trim();
        String nombre = txtNombre.getText().trim();
        String especialidad = txtEspecialidad.getText().trim();
        
        // 2. Validación para no enviar nulos a Oracle
        if (identificador.isEmpty() || nombre.isEmpty() || especialidad.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error: Ningún campo puede quedar vacío.");
            return;
        }
        
        // 3. Empaquetamos (enviamos 0 en el ID porque Oracle lo autogenera)
        Modelo.Mecanico mecanico = new Modelo.Mecanico(0, identificador, nombre, especialidad);
        Dao.MecanicoDAO dao = new Dao.MecanicoDAO();
        
        // 4. Ejecutamos el guardado
        if (dao.registrarMecanico(mecanico)) {
            javax.swing.JOptionPane.showMessageDialog(null, "¡Mecánico guardado exitosamente!");
            cargarTabla();
            
            // Limpiamos las cajas
            txtIdentificador.setText("");
            txtNombre.setText("");
            txtEspecialidad.setText("");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tbMecanicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMecanicosMouseClicked
int fila = tbMecanicos.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            txtIdentificador.setText(tbMecanicos.getValueAt(fila, 1).toString());
            txtNombre.setText(tbMecanicos.getValueAt(fila, 2).toString());
            txtEspecialidad.setText(tbMecanicos.getValueAt(fila, 3).toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbMecanicosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int filaSeleccionada = tbMecanicos.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione un mecánico de la tabla.");
            return; 
        }
        
        int idMecanico = Integer.parseInt(tbMecanicos.getValueAt(filaSeleccionada, 0).toString());
        String identificador = txtIdentificador.getText().trim();
        String nombre = txtNombre.getText().trim();
        String especialidad = txtEspecialidad.getText().trim();
        
        if (identificador.isEmpty() || nombre.isEmpty() || especialidad.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ningún campo puede quedar vacío.");
            return;
        }
        
        Modelo.Mecanico mecanico = new Modelo.Mecanico(idMecanico, identificador, nombre, especialidad);
        Dao.MecanicoDAO dao = new Dao.MecanicoDAO();
        
        if (dao.modificarMecanico(mecanico)) {
            javax.swing.JOptionPane.showMessageDialog(null, "¡Mecánico modificado!");
            cargarTabla();
            txtIdentificador.setText("");
            txtNombre.setText("");
            txtEspecialidad.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  int filaSeleccionada = tbMecanicos.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione un mecánico de la tabla.");
            return; 
        }
        
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(null, 
                "¿Eliminar este mecánico permanentemente?", "Confirmar", 
                javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
                
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            int idMecanico = Integer.parseInt(tbMecanicos.getValueAt(filaSeleccionada, 0).toString());
            Dao.MecanicoDAO dao = new Dao.MecanicoDAO();
            
            if (dao.eliminarMecanico(idMecanico)) {
                javax.swing.JOptionPane.showMessageDialog(null, "¡Mecánico eliminado!");
                cargarTabla();
                txtIdentificador.setText("");
                txtNombre.setText("");
                txtEspecialidad.setText("");
            }
        }      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMecanicos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMecanicos;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
